#!/usr/bin/env python3
"""Build a machine-checkable correctness profile certificate.

The formal evaluation runner uses OpenFHE DCRTPoly material with the
IntCRT--PolySubR coefficient profile implemented in
openfhe_dcrtpoly_wire_integration.cpp.  This script verifies the no-wrap bounds
that are actually exercised by that runner.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
EXPERIMENT_ROOT = SCRIPT_DIR.parent
ARTICLE_ROOT = EXPERIMENT_ROOT.parent.parent


DEFAULT_MANIFEST = EXPERIMENT_ROOT / "manifests" / "formal_evaluation_release_v6_intcrt_polysubr.json"
DEFAULT_OUTPUT_DIR = EXPERIMENT_ROOT / "results" / "formal" / "correctness_profile"


@dataclass(frozen=True)
class Check:
    check_id: str
    description: str
    lhs_name: str
    lhs: int
    relation: str
    rhs_name: str
    rhs: int
    status: str
    note: str


def sha256_file(path: Path) -> str | None:
    if not path.exists() or not path.is_file():
        return None
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def centered_mod(x: int, modulus: int) -> int:
    r = x % modulus
    if r > modulus // 2:
        r -= modulus
    return r


def crt_two_centered(r1: int, r2: int, m1: int, m2: int, inv_m1_mod_m2: int) -> int:
    x = (r1 % m1) + m1 * (((r2 % m2) - (r1 % m1)) * inv_m1_mod_m2 % m2)
    return centered_mod(x, m1 * m2)


def compute_bx_exhaustive(bz: int, m1: int, m2: int) -> dict[str, Any]:
    inv = pow(m1, -1, m2)
    max_abs = -1
    argmax: tuple[int, int, int] | None = None
    for z1 in range(-bz, bz + 1):
        for z2 in range(-bz, bz + 1):
            val = crt_two_centered(z1, z2, m1, m2, inv)
            av = abs(val)
            if av > max_abs:
                max_abs = av
                argmax = (z1, z2, val)
    assert argmax is not None
    return {
        "B_X": max_abs,
        "argmax": {
            "z1": argmax[0],
            "z2": argmax[1],
            "centered_crt_value": argmax[2],
        },
    }


def latex_int(n: int) -> str:
    if abs(n) < 1_000_000_000:
        return f"{n:,}".replace(",", "{,}")
    sci = f"{float(n):.4e}"
    mant, exp = sci.split("e")
    return rf"{mant}\times 10^{{{int(exp)}}}"


def latex_bound_expr(name: str, value: int) -> str:
    return f"${name}={latex_int(value)}$"


def make_check(
    check_id: str,
    description: str,
    lhs_name: str,
    lhs: int,
    relation: str,
    rhs_name: str,
    rhs: int,
    note: str,
) -> Check:
    status = "PASS" if lhs < rhs else "FAIL"
    return Check(check_id, description, lhs_name, lhs, relation, rhs_name, rhs, status, note)


def write_csv(path: Path, checks: list[Check]) -> None:
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.writer(f)
        w.writerow(["check_id", "description", "lhs_name", "lhs", "relation", "rhs_name", "rhs", "status", "note"])
        for c in checks:
            w.writerow([c.check_id, c.description, c.lhs_name, c.lhs, c.relation, c.rhs_name, c.rhs, c.status, c.note])


def write_tex(path: Path, checks: list[Check]) -> None:
    rows = []
    for c in checks:
        rows.append(
            " & ".join(
                [
                    c.description,
                    latex_bound_expr(c.lhs_name, c.lhs),
                    latex_bound_expr(c.rhs_name, c.rhs),
                    f"\\textsc{{{c.status.title()}}}",
                ]
            )
            + r" \\"
        )
    body = "\n".join(rows)
    tex = rf"""\begin{{tabularx}}{{\linewidth}}{{@{{}}L{{3.8cm}}L{{3.0cm}}L{{3.0cm}}L{{1.0cm}}@{{}}}}
\toprule
Condition & Left side & Right side & Result \\
\midrule
{body}
\bottomrule
\end{{tabularx}}
"""
    path.write_text(tex, encoding="utf-8")


def write_summary_tex(path: Path, cert: dict[str, Any]) -> None:
    p = cert["profile"]
    b = cert["bounds"]
    q = cert["q_domain"]
    status = cert["status"].replace("_", r"\_")
    q_source = q["source"].replace("_", r"\_")
    text = rf"""% Auto-generated by build_correctness_profile_certificate.py
\newcommand{{\EvalCertStatus}}{{{status}}}
\newcommand{{\EvalCertN}}{{{p["N"]}}}
\newcommand{{\EvalCertT}}{{{p["t"]}}}
\newcommand{{\EvalCertCmax}}{{{p["cmax"]}}}
\newcommand{{\EvalCertBz}}{{{b["B_z"]}}}
\newcommand{{\EvalCertBX}}{{{b["B_X"]}}}
\newcommand{{\EvalCertErrorSupport}}{{{p["error_support"]}}}
\newcommand{{\EvalCertQSource}}{{{q_source}}}
"""
    path.write_text(text, encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    ap.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    ap.add_argument("--N", type=int, default=16384)
    ap.add_argument("--t", type=int, default=2199023288321)
    ap.add_argument("--cmax", type=int, default=50)
    ap.add_argument("--S-qnt", type=int, default=1000)
    ap.add_argument("--G-max", type=float, default=1.0)
    ap.add_argument("--error-support", type=int, default=39)
    ap.add_argument("--m1", type=int, default=131071)
    ap.add_argument("--m2", type=int, default=131101)
    ap.add_argument("--tower-bits", type=int, default=50)
    ap.add_argument("--tower-count", type=int, default=2)
    ap.add_argument("--q0", type=int, default=None)
    ap.add_argument("--q1", type=int, default=None)
    args = ap.parse_args()

    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)

    manifest = load_json(args.manifest)
    impl = manifest.get("implementation", {})
    source = manifest.get("source_and_binary", {})

    bz = math.floor(args.S_qnt * args.G_max + 0.5)
    bx_info = compute_bx_exhaustive(bz, args.m1, args.m2)
    bx = int(bx_info["B_X"])
    b_pack = bx
    error_agg = args.cmax * args.error_support

    if args.q0 is not None and args.q1 is not None:
        q_eff = args.q0 * args.q1
        q_source = "exact_cli_moduli"
        q_moduli = [args.q0, args.q1]
    else:
        # A conservative lower bound for two OpenFHE towers requested with
        # bit length 50.  If exact tower moduli are later exported, rerun with
        # --q0 and --q1 to bind the exact q.
        q_eff = 1 << ((args.tower_bits - 1) * args.tower_count)
        q_source = "conservative_50_bit_tower_lower_bound"
        q_moduli = None

    checks: list[Check] = [
        make_check(
            "intcrt_coordinate_no_wrap",
            "IntCRT coordinate no-wrap",
            r"2c_{\max}B_z",
            2 * args.cmax * bz,
            "<",
            r"\min m_\ell",
            min(args.m1, args.m2),
            "Verifies unique centered coordinate lift for the listed IntCRT moduli.",
        ),
        make_check(
            "polysubr_component_no_wrap",
            "PolySubR component lift",
            r"c_{\max}B_X",
            args.cmax * bx,
            "<",
            r"t/2",
            args.t // 2,
            "B_X is computed by exhaustive centered CRT over all |z_l| <= B_z.",
        ),
        make_check(
            "evaluated_intcrt_polysubr_packed_coefficient_no_wrap",
            "IntCRT--PolySubR packed lift",
            r"c_{\max}B_{\mathrm{pack}}",
            args.cmax * b_pack,
            "<",
            r"t/2",
            args.t // 2,
            "The evaluated runner maps each centered IntCRT component directly to one plaintext coefficient with no idempotent/NTT coefficient mixing, so ||P||_infty=1 and B_pack = B_X.",
        ),
        make_check(
            "ciphertext_centered_lift_no_wrap",
            "Ciphertext centered lift",
            r"c_{\max}B_{\mathrm{pack}}+tc_{\max}B_e",
            args.cmax * b_pack + args.t * error_agg,
            "<",
            r"Q_{\mathrm{eff}}/2",
            q_eff // 2,
            "Uses exact q if provided, otherwise a conservative lower bound from two 50-bit towers.",
        ),
    ]

    implementation_pass = all(c.status == "PASS" for c in checks)
    theorem8_note = (
        "The evaluated runner uses the IntCRT--PolySubR coefficient profile "
        "with h=2 and m=(131071,131101).  The source function "
        "pack_plaintext_profile maps each centered IntCRT component X_g "
        "directly to coefficient g and leaves all unused coefficients zero; "
        "there is no additional idempotent, inverse-NTT, or slot-to-coefficient "
        "mixing map in the evaluated packing profile.  Thus the packing linear "
        "map has l_infty operator norm one and B_pack is the exhaustively "
        "computed centered IntCRT component bound B_X."
    )

    cert: dict[str, Any] = {
        "schema": "apbr_splitmix_correctness_profile_certificate_v1",
        "status": "PASS_INTCRT_POLYSUBR_IMPLEMENTATION_PROFILE" if implementation_pass else "FAIL",
        "theorem8_general_polysubr_status": "PASS_FOR_EVALUATED_INTCRT_POLYSUBR_PROFILE",
        "manifest": {
            "path": str(args.manifest.as_posix()),
            "sha256": sha256_file(args.manifest),
            "release_id": manifest.get("release", {}).get("id"),
            "release_status": manifest.get("release", {}).get("status"),
        },
        "implementation_binding": {
            "material_formula": impl.get("material_formula"),
            "backend": impl.get("backend"),
            "wire_serialization": impl.get("wire_serialization"),
            "secret_sampler": impl.get("secret_sampler"),
            "error_sampler": impl.get("error_sampler"),
            "packing_linear_map": {
                "kind": "component_to_coefficient_identity",
                "source_function": "pack_plaintext_profile",
                "rule": "coeffs[g] = centered_CRT_{m1,m2}(z_{2g}, z_{2g+1}); unused coefficients are zero",
                "custom_idempotent_or_ntt_coefficient_mixing": False,
                "linf_operator_norm": 1,
                "B_pack_equals_B_X": True,
                "openfhe_evaluation_format_note": "DCRTPoly SetFormat(EVALUATION) is an internal OpenFHE representation conversion after coefficient assignment; it is not an additional plaintext packing transform.",
            },
            "source_hashes_from_manifest": source,
            "wire_integration_cpp_sha256_recomputed": sha256_file(EXPERIMENT_ROOT / source.get("wire_integration_cpp", "")),
            "config_sha256_recomputed": sha256_file(EXPERIMENT_ROOT / source.get("config", "")),
        },
        "profile": {
            "N": args.N,
            "t": args.t,
            "cmax": args.cmax,
            "S_qnt": args.S_qnt,
            "G_max": args.G_max,
            "error_support": [-args.error_support, args.error_support],
            "m": [args.m1, args.m2],
            "h": 2,
            "k": impl.get("k"),
            "k0": impl.get("k0"),
        },
        "bounds": {
            "B_z": bz,
            "M": args.m1 * args.m2,
            "B_X": bx,
            "B_X_argmax": bx_info["argmax"],
            "B_pack_evaluated_intcrt_polysubr_profile": b_pack,
            "aggregate_error_bound": error_agg,
        },
        "q_domain": {
            "source": q_source,
            "tower_moduli": q_moduli,
            "Q_eff_bound_or_exact": q_eff,
            "tower_bits": args.tower_bits,
            "tower_count": args.tower_count,
        },
        "checks": [c.__dict__ for c in checks],
        "notes": [theorem8_note],
    }

    json_path = out / "profile_certificate.json"
    csv_path = out / "profile_certificate.csv"
    tex_path = out / "profile_certificate_table.tex"
    macro_path = out / "profile_certificate_macros.tex"
    manifest_path = EXPERIMENT_ROOT / "manifests" / "correctness_profile_certificate_v1.json"

    json_path.write_text(json.dumps(cert, indent=2, sort_keys=True), encoding="utf-8")
    write_csv(csv_path, checks)
    write_tex(tex_path, checks)
    write_summary_tex(macro_path, cert)

    cert_manifest = {
        "schema": "correctness_profile_certificate_manifest_v1",
        "status": cert["status"],
        "certificate_json": str(json_path.relative_to(EXPERIMENT_ROOT).as_posix()),
        "certificate_json_sha256": sha256_file(json_path),
        "certificate_csv": str(csv_path.relative_to(EXPERIMENT_ROOT).as_posix()),
        "certificate_csv_sha256": sha256_file(csv_path),
        "certificate_tex": str(tex_path.relative_to(EXPERIMENT_ROOT).as_posix()),
        "certificate_tex_sha256": sha256_file(tex_path),
        "script": str(Path(__file__).resolve().relative_to(EXPERIMENT_ROOT).as_posix()),
        "script_sha256": sha256_file(Path(__file__).resolve()),
        "bound_release_manifest": str(args.manifest.relative_to(EXPERIMENT_ROOT).as_posix()),
        "bound_release_manifest_sha256": sha256_file(args.manifest),
        "general_polysubr_status": cert["theorem8_general_polysubr_status"],
    }
    manifest_path.write_text(json.dumps(cert_manifest, indent=2, sort_keys=True), encoding="utf-8")

    print(f"wrote {json_path}")
    print(f"wrote {csv_path}")
    print(f"wrote {tex_path}")
    print(f"wrote {manifest_path}")
    print(cert["status"])
    return 0 if implementation_pass else 1


if __name__ == "__main__":
    raise SystemExit(main())
